apiVersion: tools.swoll.criticalstack.com/v1alpha1
kind: Trace
metadata:
  name: swoll-argo-test
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  duration: 5m
  syscalls:
    - openat
    - execve
    - socket
    - accept4
    - listen
    - bind
    - connect
  labelSelector:
      matchLabels:
          app: guestbook-ui

