apiVersion: v1
kind: Pod
metadata:
  name: guestbook-ui   
  app: guestbook-ui
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: webserver 
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: indexwriter 
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index․html;
          sleep 1;
        done
